title: Kerry Tedford
logo: /assets/img/profilepic2.jpg
email: kerry.tedford@gmail.com
description: >
  <br>
  Data Analyst with background in ...
  <br><br>
  Extra paragraph with more info...
  <br><br>
  <a href="https://www.linkedin.com/in/kerry-tedford/">View my LinkedIn Profile</a> 

url: "https://ktedford1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
