title: Kerry Tedford
logo: /assets/img/profilepic2.jpg
email: kerry.tedford@gmail.com
description: >
  <br>
  Data Analyst with 10+ years of experience in scientific data analysis and a PhD in Immunology from Universität Würzburg, Germany. Proficient in Python, R, SQL, and Tableau. Currently studying computer science, focusing on cloud computing, machine learning, and data management.
  <br><br>
  <a href="https://www.linkedin.com/in/kerry-tedford/">View my LinkedIn Profile</a> 

url: "https://ktedford1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
